<script src="{{ asset('assets/vendors/modernizr-3.6.0.min.js') }}"></script>
<script src="{{ asset('assets/vendors/jquery-3.6.0.min.js') }}"></script>
<script src="{{ asset('assets/vendors/popper.min.js') }}"></script>
<script src="{{ asset('assets/vendors/bootstrap.min.js') }}"></script>
<script src="{{ asset('assets/vendors/jquery.slicknav.js') }}"></script>
<script src="{{ asset('assets/vendors/owl.carousel.min.js') }}"></script>
<script src="{{ asset('assets/vendors/slick.min.js') }}"></script>
<script src="{{ asset('assets/vendors/wow.min.js') }}"></script>
<script src="{{ asset('assets/vendors/animated.headline.js') }}"></script>
<script src="{{ asset('assets/vendors/jquery.magnific-popup.js') }}"></script>
<script src="{{ asset('assets/vendors/jquery.vticker-min.js') }}"></script>
<script src="{{ asset('assets/vendors/jquery.scrollUp.min.js') }}"></script>
<script src="{{ asset('assets/vendors/jquery.nice-select.min.js') }}"></script>
<script src="{{ asset('assets/vendors/perfect-scrollbar.js') }}"></script>
<script src="{{ asset('assets/vendors/waypoints.min.js') }}"></script>
<script src="{{ asset('assets/vendors/jquery.counterup.min.js') }}"></script>
<script src="{{ asset('assets/vendors/jquery.theia.sticky.js') }}"></script>
<script src="https://unpkg.com/ionicons@5.0.0/dist/ionicons.js"></script>
<script src="{{ asset('assets/vendors/main.js') }}"></script>
<script src="{{asset('assets/js/data-table.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/datatables/datatables.min.js')}}"></script>
<script src="{{asset('assets/node_modules/datatables.net-bs4/js/dataTables.bootstrap4.js')}}"></script>
<script src="{{ asset('assets/js/carousel-custom.js') }}"></script>